---
- name: Create CubeFS group
  group:
    name: cubefs
    state: present

- name: Create CubeFS user
  user:
    name: cubefs
    group: cubefs
    state: present
    shell: /bin/bash
    system: true

- name: Create CubeFS data directory
  file:
    path: "{{ cubefs_data_dir }}"
    state: directory
    owner: cubefs
    group: cubefs
    mode: 0755

- name: Create CubeFS log directory
  file:
    path: "{{ cubefs_log_dir }}"
    state: directory
    owner: cubefs
    group: cubefs
    mode: 0755

- name: Create CubeFS configuration directory
  file:
    path: /etc/cubefs
    state: directory
    owner: root
    group: root
    mode: 0755
    
- name: Set number of open files
  sysctl:
    name: fs.file-max
    value: 10240000
    state: present
    reload: yes

- name: Set up master configuration
  include_tasks: master.yml
  when: "'cubefs_master' in group_names"

- name: Set up metanode configuration
  include_tasks: metanode.yml
  when: "'cubefs_metanode' in group_names"

- name: Set up datanode configuration
  include_tasks: datanode.yml
  when: "'cubefs_datanode' in group_names"

- name: Set up cli configuration
  include_tasks: cli.yml
  when: "'cubefs_cli' in group_names"

- name: Set up client configuration
  include_tasks: client.yml
  when: "'cubefs_client' in group_names"