---
# TODO - name: Ensure the latest binaries are installed

# Ensure component services are started
- name: Start CubeFS masters
  service:
    name: cubefs-master
    state: started
    enabled: true
  when: "'cubefs_master' in group_names"

- name: Start CubeFS metanodes
  service:
    name: cubefs-metanode
    state: started
    enabled: true
  when: "'cubefs_metanode' in group_names"

- name: Start CubeFS datanodes
  service:
    name: cubefs-datanode
    state: started
    enabled: true
  when: "'cubefs_datanode' in group_names"

- name: Start CubeFS object gateways
  service:
    name: cubefs-object-gateway
    state: started
    enabled: true
  when: "'cubefs_object_gateway' in group_names"
