---
- name: Install CubeFS master systemd service
  template:
    src: master.service.j2
    dest: /etc/systemd/system/cubefs-master.service
    owner: root
    group: root
    mode: 0755
  notify:
    - Reload systemd

- name: Install CubeFS master configuration
  template:
    src: master.cfg.j2
    dest: /etc/cubefs/master.cfg
    owner: cubefs
    group: cubefs
    mode: 0700
  notify:
    - Reload systemd
