---
- name: Install CubeFS metanode systemd service
  template:
    src: metanode.service.j2
    dest: /etc/systemd/system/cubefs-metanode.service
    owner: root
    group: root
    mode: 0755
  notify:
    - Reload systemd

- name: Install CubeFS metanode configuration
  template:
    src: metanode.cfg.j2
    dest: /etc/cubefs/metanode.cfg
    owner: cubefs
    group: cubefs
    mode: 0700
  notify:
    - Reload systemd
